export const GOOGLE_BUSINESS_CATEGORIES = [
    { label: "Accounting", value: "Accounting" },
    { label: "Agency", value: "Agency" },
    { label: "Agriculture", value: "Agriculture" },
    { label: "Automotive", value: "Automotive" },
    { label: "Bakery", value: "Bakery" },
    { label: "Bar & Nightlife", value: "Bar & Nightlife" },
    { label: "Beauty & Spa", value: "Beauty & Spa" },
    { label: "Cafe", value: "Cafe" },
    { label: "Construction", value: "Construction" },
    { label: "Consulting", value: "Consulting" },
    { label: "Dentist", value: "Dentist" },
    { label: "E-commerce", value: "E-commerce" },
    { label: "Education", value: "Education" },
    { label: "Engineering", value: "Engineering" },
    { label: "Entertainment", value: "Entertainment" },
    { label: "Event Planning", value: "Event Planning" },
    { label: "Finance", value: "Finance" },
    { label: "Government", value: "Government" },
    { label: "Grocery & Food", value: "Grocery & Food" },
    { label: "Gym & Fitness", value: "Gym & Fitness" },
    { label: "Health & Medical", value: "Health & Medical" },
    { label: "Home Services", value: "Home Services" },
    { label: "Hotel & Accommodation", value: "Hotel & Accommodation" },
    { label: "Insurance", value: "Insurance" },
    { label: "Legal", value: "Legal" },
    { label: "Manufacturing", value: "Manufacturing" },
    { label: "Marketing & Advertising", value: "Marketing & Advertising" },
    { label: "Media & Publishing", value: "Media & Publishing" },
    { label: "Non-Profit", value: "Non-Profit" },
    { label: "Personal Care", value: "Personal Care" },
    { label: "Photography", value: "Photography" },
    { label: "Plumbing", value: "Plumbing" },
    { label: "Real Estate", value: "Real Estate" },
    { label: "Restaurant", value: "Restaurant" },
    { label: "Retail", value: "Retail" },
    { label: "Software & Technology", value: "Software & Technology" },
    { label: "Sports & Recreation", value: "Sports & Recreation" },
    { label: "Transportation", value: "Transportation" },
    { label: "Travel & Tourism", value: "Travel & Tourism" },
    { label: "Veterinary", value: "Veterinary" },
    { label: "Wholesale", value: "Wholesale" },
    { label: "Other", value: "Other" }
];
